### ISSUE TITLE
Foreign characters cause the reader to crash in an arithmetic overflow

### ISSUE THREAD

**Issue by BlobCodes** [crystal-term/reader#1]
First, thank you for those awesome libraries.
The reader has a problem with exotic / foreign characters (e.g. ßäĳツ).
Some of those characters are just not received correctly and thus shown as a question mark, others instantly crash the program.

![Screenshot_20200612_220100](https://user-images.githubusercontent.com/14961554/84541728-3b00da80-acf8-11ea-9bcb-83493043821f.png)

Tested on Crystal 0.35.0, term-reader 0.1.0 at 69dcdec

**Comment by BlobCodes** [comment]
This is the backtrace:
![Screenshot_20200612_220400](https://user-images.githubusercontent.com/14961554/84541898-a3e85280-acf8-11ea-8ade-c78d3b2487d3.png)

**Comment by watzon** [comment]
Thanks for this, I'll look into it! Want to give me some example inputs to use?

**Comment by BlobCodes** [comment]
Example of a character not being registered correctly: ß
Example of a character resulting in an exception: ツ (Basically any emoji or eastern character)

**Comment by watzon** [comment]
This should be fixed. Let me know if you still have issues.
